#!/usr/local/bin/ruby
$VERBOSE = true

DIR = '/mnt/backups/'

servers = [5,6,7,8,9,10,11,12,13,14,15,16,17,19,20,23,26].map {|i| "dash#{i}" }
servers.each do |m|
  `rsync -avz -e "ssh -i /home/ubuntu/.ssh/production-code-org.pem" #{m}.code.org:/home/ubuntu/apps/dashboard/shared/log/milestone*.gz #{DIR}#{m}/log`

  append = (File.mtime(Dir.glob("#{DIR}/#{m}/log/milestone*.gz").sort.last) < File.mtime("#{DIR}/#{m}/log/milestone.log")) ? '--append' : ''
  `rsync -avz #{append} -e "ssh -i /home/ubuntu/.ssh/production-code-org.pem" #{m}.code.org:/home/ubuntu/apps/dashboard/shared/log/milestone.log #{DIR}#{m}/log`
  puts "#{m}.code.org #{append}"
end

`/etc/cdo/count_lines > /tmp/line_data.json`
`cp /tmp/line_data.json #{DIR}`
